const assert=require('node:assert/strict');
const {pairs,project}=require('./static/pairs.js');
const f=(id,path,extra={})=>({id,path,type:path.split('.').pop(),...extra});
const jpg=f('j','/shoot/DSC_01.JPG'),raw=f('r','/shoot/DSC_01.NEF'),other=f('o','/else/DSC_01.JPG'),png=f('p','/shoot/test.png');
assert.deepEqual(project([jpg,raw,other,png]).visible,[raw,other,png]);
assert.deepEqual(project([jpg,raw],{mode:'jpg'}).visible,[jpg]);
assert.deepEqual(project([jpg,raw],{mode:'raw'}).visible,[raw]);
assert.deepEqual(project([jpg,raw],{group:false}).visible,[jpg,raw]);
assert.deepEqual(project([jpg,raw],{preferred:new Map([['r','j']])}).visible,[jpg]);
assert.deepEqual(project([jpg,raw],{accept:f=>f.id==='j'}).visible,[jpg]);
assert.deepEqual(project([jpg,{...raw,missing:true}]).visible,[jpg]);
assert.equal(pairs([jpg,raw,f('r2','/shoot/DSC_01.RAF')]).size,0);
assert.equal(pairs([{...jpg,capture_time:'a'},{...raw,capture_time:'b'}]).size,0);
assert.equal(pairs([jpg,other]).size,0);
const before=JSON.stringify([jpg,raw]);project([jpg,raw]);assert.equal(JSON.stringify([jpg,raw]),before);
console.log('11 pairing assertions passed');
const {hasEdits}=require('./static/pairs.js');
const defaults={preset:'neutral',exposure:0,masks:[],crop:[0,0,1,1],tone_engine:1};
assert.equal(hasEdits({},defaults),false);
assert.equal(hasEdits({...defaults},defaults),false);
assert.equal(hasEdits({...defaults,exposure:1},defaults),true);
assert.equal(hasEdits({...defaults,crop:[0,0,.5,1]},defaults),true);
assert.equal(hasEdits({...defaults,masks:[{type:'brush',strokes:[]}]},defaults),true);
assert.equal(hasEdits({...defaults,preset:'another-label'},defaults),false);
assert.equal(hasEdits({exposure:0,crop:[0,0,1,1],masks:[],preset:'neutral',tone_engine:1},defaults),false);
console.log('7 edit-indicator assertions passed');
